Include easyTableNavigator to translation
nvaccess/mrconfig pull request #44
Opened 2021-07-05 06:45 UTC by Oreonan

2021-07-07 08:28 UTC, CyrilleB79 commented
This does not pretend to be an exhaustive review. However I have 2 remarks:
* The following file should be created: available.d/10_easyTableNavigator. For now it is missing.
* In nvdaaddons/easyTableNavigator, the stable branch should point to the last stable version, i.e. 2.2.1. More precisely master has to be merged in the stable branch.

2021-07-07 08:35 UTC, Oreonan commented
* As I can see, 10_easyTableNavigator isn't missing: https://github.com/nvaccess/mrconfig/blob/master/available.d/10_easyTableNavigator

2021-07-07 09:02 UTC, CyrilleB79 commented
> * As I can see, 10_easyTableNavigator isn't missing: https://github.com/nvaccess/mrconfig/blob/master/available.d/10_easyTableNavigator

Sorry, my bad.
Only the other point is relevant.

2021-07-21 09:13 UTC, feerrenrut requested changes
Please confirm the following command works on the stable branch of the add-on:
`scons pot mergePot`

2021-07-21 09:13 UTC, feerrenrut commented on automatic.crontab
> +00  5 * * fri $AddonTranslationUpdate easyTableNavigator
Please add `easyTableNavigator` at the of the 'e' section. At '20 5 * * fri $AddonTranslationUpdate easyTableNavigator`

2021-07-21 09:33 UTC, Oreonan commented
I've made a commit on my repo to make scons pot mergePot working

2021-07-21 12:01 UTC, CyrilleB79 commented
@Oreonan, as already written before, you need to merge the `master` branch into the `stable` branch and push the `stable` branch in the `nvdaaddons` repo. Else, you won't get any translatable string.

2021-07-21 12:13 UTC, Oreonan commented
I'm waiting an invitation to nvdaaddons to do this. I requested this 
this morning to Noelia.

2021-07-21 13:36 UTC, Oreonan commented
It's now did.

2021-07-22 06:04 UTC, feerrenrut commented
Thanks for making the updates here. Though having now been through this process with a number of other add-on's it is probably easier for me to do this manually. I'm going to close this PR and replace it with a new issue with the [Addon registration template](https://github.com/nvaccess/mrconfig/issues/new/choose): https://github.com/nvaccess/mrconfig/issues/49

2021-07-22 06:04 UTC, closed without merging